services:
  - type: web
    name: bulbul-schedule
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_PATH
        value: /opt/render/project/data/salary.db
    disk:
      name: data
      mountPath: /opt/render/project/data
      sizeGB: 1
